// import { IFuncionarioInterface } from "../interfaces/funcionario";
export class FuncionarioModel {
  public id: number;
  public matriculaId: undefined;
  public nomeCompleto: string;
  public cpf: string;
  public rg: string;
  public orgaoEmissor: string;
  public genero: string;
  public estadoCivil: string;
  public dataNascimento?: Date;
  public dataAdmissao?: Date;
  public statusAdmissao: boolean;
  public dataDemissao?: Date;
  public cargo: string;
  public setorId: number;
  public endereco: string;
  public numero: number;
  public complemento: string;
  public cep: string;
  public bairro: string;
  public cidade: string;
  public estado: string;
  public telefone: string;
  public telefone2: string;
  public email: string;
  public observacoes: string;
  public salario?: number;
  public foto?: string;
  public site: string;

  constructor() {
    this.id = 0;
    this.matriculaId = undefined;
    this.nomeCompleto = '';
    this.cpf = '';
    this.rg = '';
    this.orgaoEmissor = '';
    this.genero = '';
    this.estadoCivil = '';
    this.dataNascimento = undefined;
    this.dataAdmissao = undefined;
    this.statusAdmissao = false;
    this.dataDemissao = undefined;
    this.cargo = '';
    this.setorId = 0;
    this.endereco = '';
    this.numero = 0;
    this.complemento = '';
    this.cep = '';
    this.bairro = '';
    this.cidade = '';
    this.estado = '';
    this.telefone = '';
    this.telefone2 = '';
    this.email = '';
    this.observacoes = '';
    this.salario = undefined;
    this.foto = undefined;
    this.site = '';
  }
}